export const ROUTES = {
  root: '/',
  orderEdit: '/order/:groupID/editing',
  orderPrint: '/order/:groupID/print',
  order: '/order/:groupID',
  priceModifiers: '/price-modifiers',
  customers: '/customers',
  materials: '/materials',
  colors: '/colors',
  facadePanels: '/facade-panels',
  facadeProfiles: '/facade-profiles',
  patinas: '/patinas',
  varnishes: '/varnishes',
  productionOperations: '/production-operations',
  products: '/products',
};
